info:
  app:
    name: studies
    description: Studies Module
    version: 1.0
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    client-secret: XY7kmzoNzl100
    token-validity-seconds: 6060

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:oracle:thin:@HOST:PORT:SCHEMA
    username: USER
    password: PASSWORD
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver



  max-active: 10
  max-idle: 8
  max-wait: 10000
  min-evictable-idle-time-millis: 1000
  min-idle: 8
  time-between-eviction-runs-millis: 1
