info:
  app:
    name: studies
    description: Studies Module
    version: 1.0
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        type: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    client-secret: XY7kmzoNzl100
    token-validity-seconds: 6060

spring:
  batch:
    initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:oracle:thin:@212.163.185.131:1521:hemohub
    username: HEMOHUB_QA_V1_6_0
    password: hemohub
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver

  properties:
    hibernate:
      show_sql: true
      format_sql: true

  max-active: 10
  max-idle: 8
  max-wait: 10000
  min-evictable-idle-time-millis: 1000
  min-idle: 8
  time-between-eviction-runs-millis: 1
